
animations = true;
animation-stiffness = 148;
animation-dampening = 32;
animation-clamping = false;
animation-mass = 0.4;

animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";

animation-exclude = [
    "class_g = 'Polybar'",
    "window_type = 'dock'"
];

#           Corners             #

corner-radius = 0;
rounded-corners-exclude = [
  "window_type = 'desktop'"
];


#             Blur              #

blur: {
  method = "dual_kawase";
  strength = 5;      # Higher strength = More "Frosted"
  background = true;  # REQUIRED for glass effect
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

#      Backend & Performance    #

backend = "xrender"; # "xrender" is fallback, use "glx" or "egl" for blur and smoother animations
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;
vsync = true;


opacity-rule = [
  "90:class_g = 'Alacritty' && !focused",
  "100:class_g = 'Alacritty' && focused"
];

fading = true;
fade-in-step = 0.3;
fade-out-step = 0.3;
fade-delta = 12;

blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];
